CREATE TABLE `rooms` (
  `id` int NOT NULL AUTO_INCREMENT,
  `sdesc` varchar(100) DEFAULT NULL,
  `maxguest` varchar(100) DEFAULT NULL,
  `numbrooms` varchar(10) DEFAULT NULL,
  `date_start` varchar(45) DEFAULT NULL,
  `numbbeds` varchar(100) DEFAULT NULL,
  `numbbaths` varchar(100) DEFAULT NULL,
  `end_date` varchar(100) DEFAULT NULL,
  `dayprice` varchar(100) DEFAULT NULL,
  `weeklyprice` varchar(100) DEFAULT NULL,

  `botiquin` tinyint(1) DEFAULT NULL,
  `pestillo` tinyint(1) DEFAULT NULL,
  `extintor` tinyint(1) DEFAULT NULL,
  `ficha` tinyint(1) DEFAULT NULL,

 `cocina` tinyint(1) DEFAULT NULL,
  `internet` tinyint(1) DEFAULT NULL,
  `tv` tinyint(1) DEFAULT NULL,
  `calefaccion` tinyint(1) DEFAULT NULL,
  `aire` tinyint(1) DEFAULT NULL,
  `mascotas` tinyint(1) DEFAULT NULL,
  `basicos` tinyint(1) DEFAULT NULL,
  `parking` tinyint(1) DEFAULT NULL,
  `rutas` tinyint(1) DEFAULT NULL,

`country` varchar(100) DEFAULT NULL,
`province` varchar(100) DEFAULT NULL,
`city` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `avatar` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
